name: Build Distributable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: sudo apt-get install java-common
    - name: Make executables
      run: make 
    - name: Upload redistributable zip
      uses: actions/upload-artifact@v2
      with:
        name: 50-60hz
        path: bin/
